# Generated by Django 5.2.3 on 2025-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('crop_result', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
